name: Continuous Deploy
on:
    push:
        types: [main]
    pull_request:
        branches: [main]
        types: [closed]
jobs:
    publish:
        name: publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: test
              run: yarn test
            - name: install
              run: yarn
            - name: build
              run: yarn build
            - name: publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
