name: 'Chromatic Deployment'
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create .env
        run: |
          touch .env
          echo HOLIDAY_API_KEY=${{ secrets.HOLIDAY_API_KEY }} >> .env
          echo HOLIDAY_API_URL=${{ secrets.HOLIDAY_API_URL }} >> .env
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
